steps:
# Eliminar la carpeta /workspace si existe
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - 'rm -rf /workspace || true'

# Clonar el repositorio en /workspace/backend
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/UNIZAR-30226-2023-04/backend', '/workspace/backend']

# Construir la imagen de Docker
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/crucial-mender-384310/backenddecibely', '-f', '/workspace/backend/Dockerfile', '/workspace/backend']

# Empujar la imagen de Docker a gcr.io
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/crucial-mender-384310/backenddecibely']

  
# Desplegar la aplicación en Google Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'backend'
  - '--image'
  - 'gcr.io/crucial-mender-384310/backenddecibely'
  - '--region'
  - 'europe-west1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--concurrency'
  - '80'
  - '--timeout'
  - '180s'
  - '--memory'
  - '256Mi'
  - '--set-env-vars'
  - 'MONGODB_URI=mongodb+srv://admin:admin@decibelycluster.k3opvfs.mongodb.net/?retryWrites=true&w=majority'

images:
- 'gcr.io/crucial-mender-384310/backenddecibely'
